### ISSUE TITLE
Porting new version to Android/Java.

### ISSUE THREAD

**Issue by graya4** [gjtorikian/Earthbound-Battle-Backgrounds-JS#36]
Hello! I'm a student who has been using the app version of this, Abstract Art, for close to 10 years at this point and I was interested in porting the JS versions with all of the improvements and bells and whistles and what not over to Android again (mainly for experience) and I was wondering if I could get in better contact with you somehow about tips on how the math behind the backgrounds work.

**Comment by gjtorikian** [comment]
Not sure what you mean by “better contact”—feel free to ask your question here.

**Comment by graya4** [comment]
Sure thing! I was wondering if you still had (or at least know where to find) the original background generation code that Mr.Accident had and documented all of those years ago. I tried searching through the forums but as it is a near decades long post, it'd probably be more practical to just ask.

If you dont have that I would also appreciate an explanation (whenever you have free time of course!) on how most of the math behind the background generation works.

Thanks for the quick reply too!

**Comment by gjtorikian** [comment]
Yup, I know exactly where it is: https://forum.starmen.net/forum/Fan/Games/Kraken-EB-Battle-Animation-Screensaver/first

Going to close this (just because I like to keep my issues as resolved), but feel free to ask any other questions. As you noted I don't think I've tried running this in a decade, either, so I hope the code still compiles.
